### ISSUE TITLE
Remove 'Example' target

### ISSUE THREAD

**Issue by apascual** [shibapm/PackageConfig#15]
Hi,

Swift Package Manager has issues when two dependencies contain the same target name (https://forums.swift.org/t/multiple-target-issue-with-spm/16696).

The targets should be named properly to avoid conflicts with other libraries.

**Comment by minuscorp** [comment]
I haven't jumped into this issue, can we confirm that this is still an issue with SPM?

**Comment by djbe** [comment]
I can confirm this is still an issue with Swift 5.5 (Xcode 13.2.1).
> error: multiple targets named 'Example' in: 'packageconfig', 'swifter'

**Comment by minuscorp** [comment]
I'll make a PR during the next week.
