### ISSUE TITLE
Fail to run via Mint

### ISSUE THREAD

**Issue by shimastripe** [shibapm/PackageConfig#18]
I use to Komondor via [Mint](https://github.com/yonaskolb/Mint).
But Komondor fail and error messages are below.

```
$ mint run Komondor
🌱 Cloning Komondor 1.0.6
🌱 Resolving package
🌱 Building package
🌱 Installed Komondor 1.0.6
🌱 Running komondor 1.0.6...
dyld: Library not loaded: @rpath/libPackageConfig.dylib
  Referenced from: /usr/local/lib/mint/packages/github.com_shibapm_Komondor/build/1.0.6/komondor
  Reason: image not found
[1]    52719 abort      mint run Komondor
```

How to resolve this dylib path? Please teach me any information.

**Comment by orta** [comment]
This is likely an issue with PackageConfig - you're welcome to look into it

**Comment by shimastripe** [comment]
[Mint@0.17.2](https://github.com/yonaskolb/Mint/releases/tag/0.17.2) copies all dylib files in build artifacts.
So I checked this problem is closed. Thanks!
