### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by cszatma** [shibapm/PackageConfig#6]
The issue is due to the fact that `xcrun` is called which does not exist on linux.
https://github.com/shibapm/PackageConfig/blob/89d196830ebc6b3d7fdead6391b5ae9230883b87/Sources/PackageConfig/Package.swift#L10

What is the reason for using `xcrun` vs just doing something like `command -v swiftc` to get the path to the `swiftc` binary?

**Comment by f-meloni** [comment]
I think on Danger-Swift we use `which swiftc`, and it could probably work on this case too

**Comment by cszatma** [comment]
Cool, I'll submit a fix. Just wanted to know what the reason was before I did that.

**Comment by IgorMuzyka** [comment]
@cszatma great work, thanks. 👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by cszatma** [comment]
@f-meloni do you mind releasing a new version of the package? This issue was causing Komondor to not work on linux due to it relying on this package to read its configuration.

**Comment by f-meloni** [comment]
Yes sure, will release it now :)

**Comment by f-meloni** [comment]
just pushed the tag 0.11.0

**Comment by cszatma** [comment]
Awesome, thanks!
